
export const FETCH_HOTELS_DATA_SUCCESS = "FETCH_HOTELS_DATA_SUCCESS"
export const FETCH_HOTELS_DATA_REQUEST = "FETCH_HOTELS_DATA_LOADING"
export const FETCH_HOTELS_DATA_FAILURE = "FETCH_HOTELS_DATA_FAILURE"